force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Identification</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Answer_A__c.field-meta.xml
<CustomField>
    <fullName>Answer_A__c</fullName>
    <label>Answer_A</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer_B__c.field-meta.xml
<CustomField>
    <fullName>Answer_B__c</fullName>
    <label>Answer_B</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer_C__c.field-meta.xml
<CustomField>
    <fullName>Answer_C__c</fullName>
    <label>Answer_C</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer_D__c.field-meta.xml
<CustomField>
    <fullName>Answer_D__c</fullName>
    <label>Answer_D</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer_E__c.field-meta.xml
<CustomField>
    <fullName>Answer_E__c</fullName>
    <label>Answer_E</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Certification_Exam__c.field-meta.xml
<CustomField>
    <fullName>Certification_Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certification Exam</label>
    <referenceTo>Certification_Exam__c</referenceTo>
    <relationshipLabel>Question</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <label>Correct Answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ExamPageController.cls
public with sharing class ExamPageController {
    @AuraEnabled(cacheable=true)
    public static List<Certification_Exam__c> getCertifications(){
        try {
            return [SELECT Id, Name FROM Certification_Exam__c];   
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Question__c> getQuestions(Id certId, Integer numberOfQuestions){
        try {
            List<Question__c> response = new List<Question__c> ();
            List<Question__c> questions = [SELECT Id, Question__c, Correct_Answer__c, Answer_A__c, Answer_B__c, Answer_C__c, Answer_D__c, Answer_E__c
                                                FROM Question__c WHERE Certification_Exam__c =: certId];

            response = randomizeQuestionList(questions, numberOfQuestions);
            return response;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    private static List<Question__c> randomizeQuestionList(List<Question__c> lst, Integer numberOfQuestions){
        integer currentIndex = lst.size();
        Question__c question;
        integer randomIndex;
        List<Question__c> reponse = new List<Question__c>();
        while (0 != currentIndex) {
            // Pick a remaining element...
            randomIndex = integer.valueOf(Math.floor(Math.random() * currentIndex));
            currentIndex -= 1;
            question = lst[currentIndex];
            lst[currentIndex] = lst[randomIndex];
            lst[randomIndex] = question;
        }
        if(lst.size() >= numberOfQuestions){
            for (Integer i = 0; i< numberOfQuestions; i++) {
                reponse.add(lst[i]);
            }
        }else{
            for (Integer i = 0; i< lst.size(); i++) {
                reponse.add(lst[i]);
            }
        }
        
        return reponse;
    }
}